### PR TITLE
Fix/mtl in separate lines

### PR DESCRIPTION
**Pull request by nicolas-schreiber**
Not sure if somebody else had this problem, but for me when using this tool with the YCB Dataset the materials were broken because all values were written into the files without any newlines and even without spaces.
But maybe that is more of a local issue.
Still, following small change fixed it for me

### CODE REVIEW

**Comment by kevinzakka** [comment]
Hi @nicolas-schreiber, I've not come across this issue. Could you attach an OBJ file so I can reproduce and debug?

Thanks

**Comment by nicolas-schreiber** [comment]
Sure, I usually use the YCB Objects from here: http://ycb-benchmarks.s3-website-us-east-1.amazonaws.com/
(I recommend just using any of the google-16k ones)
Then i run obj2mjcf with `--save-mtl --save-mjcf`

**Comment by kevinzakka** [comment]
Thanks for catching this @nicolas-schreiber! I'm going to submit a fix and add some comments to clarify the MTL parsing (I took a look at the code today and was like wow, what was I doing here exactly lol). Closing this PR :) Thanks again!

**Comment by nicolas-schreiber** [comment]
Glad to be of help, thank you for this tool, its making my life a lot easier

**Comment by kevinzakka** [comment]
Glad to hear! Are there other things you would find useful from this library?

As a side note, I was thinking of taking the YCB objects and creating a MuJoCo database similar to what I did with the [Scanned Objects](https://github.com/kevinzakka/mujoco_scanned_objects) dataset.

**Pull request closed without merging**
