### PR TITLE
VHACD -> CoACD.

### PR DESCRIPTION
**Pull request by kevinzakka**

### CODE REVIEW

**Comment by kevinzakka** [comment]
@kwesiRutledge Could you give this branch a spin and let me know if it works for your needs as well?

**Comment by kwesiRutledge** [comment]
Beautiful! This works for our purposes. We may want to expose more of the CoACD args to the CLI in the future, but this solves our current issues! Thanks, @kevinzakka !

**Comment by kevinzakka** [comment]
@kwesiRutledge Added the rest of the CoACD args. Going to merge with main and then push a new release. Thanks for trying it out!

**Comment by ferrolho** [comment]
Just curious: what was the reason to switch from https://github.com/kmammou/v-hacd to https://github.com/SarahWeiii/CoACD? Thanks!

**Comment by yuvaltassa** [comment]
👏

**Pull request merged**
